name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: false
      matrix:
        include:
          - shield: lily58_left
            board: nice_nano_v2
          - shield: lily58_right
            board: nice_nano_v2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: config

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ hashFiles('**/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr Export
        run: west zephyr-export

      - name: West Build
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }}

      - name: Rename Build Artifact
        run: cp build/zephyr/zmk.uf2 ${{ matrix.shield }}-${{ matrix.board }}-zmk.uf2

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ${{ matrix.shield }}-${{ matrix.board }}-zmk.uf2

  combine:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware

      - name: Display structure of downloaded files
        run: ls -R firmware

      - name: Upload Combined Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lily58-zmk-firmware
          path: firmware/*.uf2
